### ISSUE TITLE
Enhancement option

### ISSUE THREAD

**Issue by FreshImmuc** [Adir-SL/MotionBlurJS#2]
add the option to set the delay between each motion blur "frame"

**Comment by Adir-SL** [comment]
I did add this (finally),
please see the readme under
the section called "**Adding more ghosts**".
[Link to the section](https://github.com/Adir-SL/MotionBlurJS?tab=readme-ov-file#adding-more-ghosts)

Thanks for the suggestion. 🙏🏼
